//@version=4
study("AD", shorttitle="A/D", precision=1, overlay=false)

// A/D
showSignal = input(title="Show Signal ?", type=input.bool, defval=true)
signalType = input(title="Signal Smoothing Type", defval="SMA", options=["EMA", "SMA"])
signalLength = input(title="Signal Smoothing Length", type=input.integer, defval=21)
highlightCrossovers = input(title="Highlight Crossovers ?", type=input.bool, defval=false)
applyFilling = input(title="Apply Ribbon Filling ?", type=input.bool, defval=true)

signal = signalType == "EMA" ? ema(accdist, signalLength) : sma(accdist, signalLength)

trendColor = accdist > signal ? #0ebb23 : color.red

adColor = applyFilling ? trendColor : #0094ff
signalColor = applyFilling ? trendColor : #ff6a00

adPlot = plot(accdist, title="Accum/Dist", linewidth=2, color=adColor, transp=0)
signalPlot = plot(showSignal ? signal : na, title="Signal", color=signalColor, transp=0)

transparent = color.white

fillColor = applyFilling ? trendColor : transparent
fill(adPlot, signalPlot, color=fillColor, transp=70)

plotshape(crossover(accdist, signal) and highlightCrossovers ? accdist : na, title="Crossover", location=location.absolute, style=shape.circle, size=size.tiny, color=color.green, transp=0)
plotshape(crossunder(accdist, signal) and highlightCrossovers ? accdist : na, title="Crossunder", location=location.absolute, style=shape.circle, size=size.tiny, color=color.red, transp=0)


