// this creates an alert when price is out of bollinger band
study(title="out BB", overlay=false)


price = input(close)

// bolliger band
BB_length = input(50, minval=1, title="BB Length")
BB_sdev = input(2.0, minval=0.001, maxval=50, title="BBX")
dev = BB_sdev * stdev(close, BB_length)
upper = sma(close, BB_length) + dev
lower = sma(close, BB_length) - dev
p1 = plot(upper, title="Upper", color=#2B8A84)
p2 = plot(lower, title="Lower", color=#2B8A84)

// crossover upper line
c1 = crossover(price, upper)

// cross under lower line
c2 = crossunder(price, lower)
alertcondition(c1 or c2, title='Price is out of BB', message='Price is out of BB')

